server:
  port: 8050

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcb_users
    username: root
    password:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

management:
  tracing:
    sampling:
      probability: 1.0

mcb:
  auth:
    jwtExpirationMs: 86400000
    jwtSecret: ThiSisKeyAtHomeSecretTryHomeNot

microservice:
  security:
    salt: WZeBXmCI9cAz3LyY9Sdllj9l5iPsXC