server:
  port: 8085

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/
      
logging:
  pattern: 
    console: "%d{yyyy-MM-dd HH:mm:ss} [%X{traceId:-},%X{spanId:-}] ${LOG_LEVEL_PATTERN:-%5p} %m%n"

springdoc:
  packagesToScan: com.mcbproperty.documents

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mcb_users
    username: root
    password:

  jpa:
    database: mysql
    hibernate:
      ddl-auto: update

  output:
    ansi:
      enabled: always

  servlet:
    multipart:
      maxFileSize: 10MB
      maxRequestSize: 10MB

management:
  tracing:
    sampling:
      probability: 1.0